### ISSUE TITLE
Failed to install plugin on 19.5 Matrix

### ISSUE THREAD

**Issue by alienff** [vladd11/immich-kodi#1]
Thank for the plugin!
Unfortunately, I was not able to install it :( I downloaded the zip, put in in /tmp and then went to "install from zip". Kodi showed an error: "Failed to install add-on from zip file. Installing the add-on file located at /tmp/plugin.vladd11.immich.zip failed due to an invalid structure."

**Comment by vladd11** [comment]
I see. Added support to Kodi 19+
Try to use lastest release

**Comment by alienff** [comment]
Thanks! Installs now.
