### ISSUE TITLE
Not displaying all the Albums

### ISSUE THREAD

**Issue by gregeeh** [vladd11/immich-kodi#3]
Hi,

Thanks for the Add-on, but I only get 4 Albums listed when there are many more.  Is this the expected behaviour at the present time?

TIA

**Comment by vladd11** [comment]
Hello. It looks like we display only shared albums.
Please try to use this version:
[immich-kodi-testing.zip](https://github.com/user-attachments/files/18131930/immich-kodi-testing.zip)

**Comment by gregeeh** [comment]
Thanks for the prompt reply.

Yes, much better, thank you.

What will be in the final release, shared or all?

**Comment by vladd11** [comment]
Now we show all albums.
If we need to show only shared, there is an option in settings.
New release: https://github.com/vladd11/immich-kodi/releases/tag/prerelease-2

https://github.com/vladd11/immich-kodi/pull/5
