### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by agross** [vladd11/immich-kodi#4]
> Install this addon from [...] official repository

Which category is this plugin in? At least there is no Immich plugin in the official plugin's [Picture Add-on section](https://kodi.tv/addons/omega/category/picture-addons/).

[Plugin search](https://kodi.tv/addons/omega/search/) also yields no results.

**Comment by vladd11** [comment]
Hello. Sorry for inconvience. I was ready to submit this plugin when this README was written, however we find and fixed some flaws with regional settings & non-optimal solutions (such as reverse proxy to properly open images in Kodi).
